version: "3.9"
services:
  nodered:
    container_name: nodered
    hostname: nodered
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Zurich
    volumes:
      - nodered:/data

    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.nodered.rule=Host(`nodered.hetzner.basanet.net`)
      - traefik.http.routers.nodered.entrypoints=web-secure
      - traefik.http.routers.nodered.tls.certresolver=le
      - traefik.http.routers.nodered.service=nodered-service
      - traefik.http.services.nodered-service.loadbalancer.server.port=1880
    networks:
      - private

volumes:
  nodered:
    name: nodered

networks:
  private:
    external: true
