version: "3.9"
services:
  traefik:
    container_name: traefik
    hostname: traefik
    image: traefik:latest
    environment:
      - TZ=Europe/Zurich
    command:
      - --log.level=INFO
      - --log.filePath=/logs/traefik.log
      - --entrypoints.web.address=:80
      - --entrypoints.web-secure.address=:443
      - --entrypoints.dns-secure.address=:853
      - --providers.docker=true
      - --providers.file.directory=/configuration/
      - --providers.file.watch=true
      - --providers.docker.network=private
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=private
      - --providers.docker.exposedbydefault=false
      - --api.insecure=true
      - --api.dashboard=true
      - --accesslog=true
      - --accesslog.filepath=/logs/access.log
      - --accesslog.format=json
      - --serverstransport.insecureskipverify=true
      - --certificatesresolvers.le.acme.email=it+admin@basanet.net
      - --certificatesresolvers.le.acme.storage=/configuration/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --serverstransport.insecureskipverify=true
    
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - traefik_configuration:/configuration
      - traefik_logs:/logs
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`proxy.hetzner.basanet.net`)
      - traefik.http.routers.traefik.entrypoints=web-secure
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls.certresolver=le
      - traefik.http.routers.traefik.service=traefik-service
      - traefik.http.services.traefik-service.loadbalancer.server.port=8080
      - traefik.http.routers.traefik.tls.certresolver=le
      - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https      
    networks:
      - private

volumes:
  traefik_configuration:
    name: traefik_configuration
  traefik_logs:
    name: traefik_logs

networks:
  private:
    external: true
